version: '3'
services:
  my-app-node:
    image: faisalriazz/my-app-node:1.0
    ports:
      - 3001-3005:3000
  mongodb:
    image: mongo
    ports:
     - 27017:27017
    environment:
     - MONGO_INITDB_ROOT_USERNAME=admin
     - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
     - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
     - 8080:8081
    environment:
     - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
     - ME_CONFIG_MONGODB_ADMINPASSWORD=password
     - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
     - "mongodb"
  grafana:
    image: grafana/grafana:latest
    ports:
     - 5000:3000
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
     - ./datasources:/etc/grafana/provisioning/datasources
     - grafana-data:/var/lib/grafana
volumes:
  mongo-data:
    driver: local
  grafana-data:

